import { AIProvider, AIProviderName, AIProviderResponse, AIProviderToolDeclaration } from './types';
import { AgentChatMessage } from '../agent';

export class GrokProvider implements AIProvider {
  public readonly name: AIProviderName = 'grok';
  public readonly apiKey: string;
  private readonly baseUrl = 'https://api.x.ai/v1';
  private primaryModel = 'grok-2-1212';
  private readonly fallbackModels = ['grok-2', 'grok-beta'];

  constructor(apiKey: string) {
    if (!apiKey) throw new Error('Grok API Key is required');
    this.apiKey = apiKey;
  }

  public async generateResponse(params: {
    systemInstruction: string;
    history?: AgentChatMessage[];
    prompt: string;
    tools?: AIProviderToolDeclaration[];
  }): Promise<AIProviderResponse> {
    try {
      const { systemInstruction, history = [], prompt, tools = [] } = params;

      const toolDefs = tools.map(tool => ({
        type: 'function',
        function: {
          name: tool.name,
          description: tool.description,
          parameters: tool.parameters
        }
      }));

      const messages: any[] = [
        { role: 'system', content: systemInstruction },
        ...history.slice(-6).map(h => ({ role: h.role, content: h.content })),
        { role: 'user', content: prompt }
      ];

      const candidateModels = Array.from(new Set([this.primaryModel, ...this.fallbackModels]));
      let lastErrorText = '';
      let grokResponse: Response | null = null;

      for (const modelName of candidateModels) {
        const res = await fetch(`${this.baseUrl}/chat/completions`, {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${this.apiKey}`,
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            model: modelName,
            messages,
            tools: toolDefs.length > 0 ? toolDefs : undefined,
            tool_choice: toolDefs.length > 0 ? 'auto' : undefined,
            temperature: 0.2,
            max_tokens: 400
          }),
          signal: AbortSignal.timeout(5000)
        });

        if (res.ok) {
          this.primaryModel = modelName;
          grokResponse = res;
          break;
        }

        const errText = await res.text();
        lastErrorText = errText;

        // If authentication error, fail immediately
        if (res.status === 401 || res.status === 403) {
          throw new Error(`xAI Grok API error (${res.status}): ${errText}`);
        }
      }

      if (!grokResponse) {
        throw new Error(`xAI Grok API error: ${lastErrorText}`);
      }

      const data = await grokResponse.json();
      const choiceMessage = data.choices?.[0]?.message;

      if (choiceMessage?.tool_calls && choiceMessage.tool_calls.length > 0) {
        const toolCalls = choiceMessage.tool_calls.map((tc: any) => {
          let parsedArgs = {};
          try {
            parsedArgs = JSON.parse(tc.function?.arguments || '{}');
          } catch (e) {}
          return {
            name: tc.function?.name || '',
            args: parsedArgs
          };
        });

        return {
          success: true,
          toolCalls
        };
      }

      if (choiceMessage?.content) {
        return {
          success: true,
          text: choiceMessage.content
        };
      }

      return {
        success: false,
        error: 'No text or tool call generated by Grok.'
      };
    } catch (err: any) {
      console.error('[GrokProvider Error]:', err?.message || err);
      return {
        success: false,
        error: err?.message || 'Grok API call failed'
      };
    }
  }

  public async testConnection(): Promise<{ success: boolean; message: string }> {
    try {
      // First try fetching available models from xAI Console
      const modelsRes = await fetch(`${this.baseUrl}/models`, {
        method: 'GET',
        headers: {
          'Authorization': `Bearer ${this.apiKey}`
        },
        signal: AbortSignal.timeout(5000)
      });

      if (modelsRes.ok) {
        const modelsData = await modelsRes.json().catch(() => null);
        const availableModelIds: string[] = Array.isArray(modelsData?.data)
          ? modelsData.data.map((m: any) => m.id)
          : [];

        if (availableModelIds.length > 0) {
          const matched = availableModelIds.find(id =>
            id === 'grok-2-1212' || id === 'grok-2' || id === 'grok-beta' || id.includes('grok')
          );
          if (matched) {
            this.primaryModel = matched;
          }
        }

        return {
          success: true,
          message: '✓ Grok connection successful! API key is active and ready.'
        };
      }

      // Fallback: Test chat completions with candidate models
      const candidateModels = Array.from(new Set([this.primaryModel, ...this.fallbackModels]));
      let lastStatus = 400;
      let lastErrText = '';

      for (const modelName of candidateModels) {
        const chatRes = await fetch(`${this.baseUrl}/chat/completions`, {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${this.apiKey}`,
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            model: modelName,
            messages: [{ role: 'user', content: 'Ping' }],
            max_tokens: 5
          }),
          signal: AbortSignal.timeout(5000)
        });

        if (chatRes.ok) {
          this.primaryModel = modelName;
          return {
            success: true,
            message: '✓ Grok connection successful! API key is active and ready.'
          };
        }

        lastStatus = chatRes.status;
        lastErrText = await chatRes.text();

        if (chatRes.status === 401 || chatRes.status === 403 || lastErrText.includes('api_key') || lastErrText.includes('Unauthorized')) {
          return {
            success: false,
            message: 'Invalid xAI Grok API key. Please check your key in xAI Console and try again.'
          };
        }
      }

      return {
        success: false,
        message: `Grok connection failed (${lastStatus}): ${lastErrText || 'Invalid API Key'}`
      };
    } catch (err: any) {
      return {
        success: false,
        message: `xAI Grok connection failed: ${err?.message || 'Network error'}`
      };
    }
  }
}
