import { AIProvider, AIProviderName, AIProviderResponse, AIProviderToolDeclaration } from './types';
import { AgentChatMessage } from '../agent';

export class GroqProvider implements AIProvider {
  public readonly name: AIProviderName = 'groq';
  public readonly apiKey: string;
  private readonly baseUrl = 'https://api.groq.com/openai/v1';
  private primaryModel = process.env.GROQ_MODEL || 'llama-3.3-70b-versatile';
  private readonly fallbackModels = ['llama-3.1-8b-instant', 'llama3-70b-8192', 'mixtral-8x7b-32768'];

  constructor(apiKey: string) {
    if (!apiKey) throw new Error('Groq API Key is required');
    this.apiKey = apiKey;
  }

  private formatErrorMessage(status: number, errText: string): string {
    let detail = '';
    try {
      const json = JSON.parse(errText);
      detail = json.error?.message || json.error || json.message || '';
    } catch (e) {}

    if (status === 401 || errText.includes('api_key') || errText.includes('Unauthorized') || errText.includes('invalid_api_key')) {
      return 'Invalid Groq API key. Please check your key at https://console.groq.com and try again.';
    }
    if (status === 403 || errText.includes('Forbidden') || errText.includes('access_denied')) {
      return 'Access denied or model forbidden for this Groq API key (403).';
    }
    if (status === 429 || errText.includes('rate_limit') || errText.includes('quota') || errText.includes('Rate limit')) {
      return 'Groq API rate limit or quota exceeded. Please try again in a few moments (429).';
    }
    if (status === 400) {
      return `Groq model or request error (400): ${detail || errText || 'Invalid Request'}`;
    }
    if (status >= 500) {
      return `Groq API service temporary error (${status}). Please try again later.`;
    }
    return `Groq connection failed (${status}): ${detail || errText || 'API Request Failed'}`;
  }

  public async generateResponse(params: {
    systemInstruction: string;
    history?: AgentChatMessage[];
    prompt: string;
    tools?: AIProviderToolDeclaration[];
  }): Promise<AIProviderResponse> {
    try {
      const { systemInstruction, history = [], prompt, tools = [] } = params;

      const toolDefs = tools.map(tool => ({
        type: 'function',
        function: {
          name: tool.name,
          description: tool.description,
          parameters: tool.parameters
        }
      }));

      const messages: any[] = [
        { role: 'system', content: systemInstruction },
        ...history.slice(-6).map(h => ({ role: h.role, content: h.content })),
        { role: 'user', content: prompt }
      ];

      const candidateModels = Array.from(new Set([this.primaryModel, ...this.fallbackModels]));
      let lastErrorStatus = 500;
      let lastErrorText = '';
      let groqResponse: Response | null = null;

      for (const modelName of candidateModels) {
        const res = await fetch(`${this.baseUrl}/chat/completions`, {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${this.apiKey}`,
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            model: modelName,
            messages,
            tools: toolDefs.length > 0 ? toolDefs : undefined,
            tool_choice: toolDefs.length > 0 ? 'auto' : undefined,
            temperature: 0.2,
            max_tokens: 400
          }),
          signal: AbortSignal.timeout(8000)
        });

        if (res.ok) {
          this.primaryModel = modelName;
          groqResponse = res;
          break;
        }

        const errText = await res.text();
        lastErrorStatus = res.status;
        lastErrorText = errText;

        if (res.status === 401 || res.status === 403 || res.status === 429) {
          throw new Error(this.formatErrorMessage(res.status, errText));
        }
      }

      if (!groqResponse) {
        throw new Error(this.formatErrorMessage(lastErrorStatus, lastErrorText));
      }

      const data = await groqResponse.json();
      const choiceMessage = data.choices?.[0]?.message;

      if (choiceMessage?.tool_calls && choiceMessage.tool_calls.length > 0) {
        const toolCalls = choiceMessage.tool_calls.map((tc: any) => {
          let parsedArgs = {};
          try {
            parsedArgs = JSON.parse(tc.function?.arguments || '{}');
          } catch (e) {}
          return {
            name: tc.function?.name || '',
            args: parsedArgs
          };
        });

        return {
          success: true,
          toolCalls
        };
      }

      if (choiceMessage?.content) {
        return {
          success: true,
          text: choiceMessage.content
        };
      }

      return {
        success: false,
        error: 'No text or tool call generated by Groq.'
      };
    } catch (err: any) {
      console.error('[GroqProvider Error]:', err?.message || err);
      return {
        success: false,
        error: err?.message || 'Groq API call failed'
      };
    }
  }

  public async testConnection(): Promise<{ success: boolean; message: string }> {
    try {
      // 1. Fetch available models from Groq API
      const modelsRes = await fetch(`${this.baseUrl}/models`, {
        method: 'GET',
        headers: {
          'Authorization': `Bearer ${this.apiKey}`
        },
        signal: AbortSignal.timeout(5000)
      });

      if (modelsRes.ok) {
        const modelsData = await modelsRes.json().catch(() => null);
        const availableModelIds: string[] = Array.isArray(modelsData?.data)
          ? modelsData.data.map((m: any) => m.id)
          : [];

        if (availableModelIds.length > 0) {
          const envModel = process.env.GROQ_MODEL;
          if (envModel && availableModelIds.includes(envModel)) {
            this.primaryModel = envModel;
          } else {
            const preferred = availableModelIds.find(id =>
              id === 'llama-3.3-70b-versatile' || id === 'llama3-70b-8192' || id.includes('llama-3')
            );
            if (preferred) {
              this.primaryModel = preferred;
            }
          }
        }

        return {
          success: true,
          message: '✓ Groq connection successful! API key is active and ready.'
        };
      }

      // 2. Fallback: Test chat completions with candidate models
      const candidateModels = Array.from(new Set([this.primaryModel, ...this.fallbackModels]));
      let lastStatus = 400;
      let lastErrText = '';

      for (const modelName of candidateModels) {
        const chatRes = await fetch(`${this.baseUrl}/chat/completions`, {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${this.apiKey}`,
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            model: modelName,
            messages: [{ role: 'user', content: 'Ping' }],
            max_tokens: 5
          }),
          signal: AbortSignal.timeout(5000)
        });

        if (chatRes.ok) {
          this.primaryModel = modelName;
          return {
            success: true,
            message: '✓ Groq connection successful! API key is active and ready.'
          };
        }

        lastStatus = chatRes.status;
        lastErrText = await chatRes.text();

        if (chatRes.status === 401 || chatRes.status === 403 || chatRes.status === 429) {
          return {
            success: false,
            message: this.formatErrorMessage(chatRes.status, lastErrText)
          };
        }
      }

      return {
        success: false,
        message: this.formatErrorMessage(lastStatus, lastErrText)
      };
    } catch (err: any) {
      return {
        success: false,
        message: `Groq connection failed: ${err?.message || 'Network error'}`
      };
    }
  }
}
