import { pgTable, text, uuid, timestamp, integer } from 'drizzle-orm/pg-core';

export const tenants = pgTable('tenants', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  slug: text('slug').notNull().unique(),
  schema_name: text('schema_name').notNull().unique(),
  domain: text('domain'),
  logo_url: text('logo_url'),
  primary_color: text('primary_color').default('#6366f1'),
  admin_email: text('admin_email').notNull(),
  stripe_customer_id: text('stripe_customer_id'),
  stripe_subscription_id: text('stripe_subscription_id'),
  plan_type: text('plan_type').default('basic'),
  billing_status: text('billing_status').default('trial'),
  trial_ends_at: timestamp('trial_ends_at', { withTimezone: true }),
  current_period_end: timestamp('current_period_end', { withTimezone: true }),
  monthly_amount_inr: integer('monthly_amount_inr').default(2999),
  max_students: integer('max_students').default(500),
  max_courses: integer('max_courses').default(50),
  max_storage_gb: integer('max_storage_gb').default(10),
  status: text('status').default('active'),
  created_at: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updated_at: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});
